 <h3>OvalFleet Service Terms</h3>
 <ul>
   <li>OvalFleet is responsible for providing a quality customer experience and reinforces a commitment that focuses on friendly and helpful service.</li>
   <li>Your use of our service and/or products shall comply with all applicable domestic and international laws, statutes, ordinances and regulations.</li>
   <li>Without limiting any other remedies, OvalFleet may suspend or terminate your account if we suspect that you (by conviction, settlement, insurance or escrow investigation, or otherwise) have engaged in fraudulent activity in connection with our services.</li>
   <li>In the event we introduce a new service and/or product, the fees for that service and/or product are effective at the launch of the service and/or product. Unless otherwise stated, all fees are quoted in U.S. Dollars.</li>
   <li>Our services and products are available only to, and may only be used by individuals who can form legally binding contracts under applicable law. Without limiting the foregoing, our services and products are not available to children (persons under the age of 18). If you are under the age of 18, you can use our services and/or products only in conjunction with, and under the supervision of your parents or guardians. If you do not qualify, please do not use our Site, Services and Products. Further, your OvalFleet account (including feedback) and User ID may not be transferred or sold to another party.</li>
   <li>OvalFleet reserves the right to change or modify any of the terms and conditions contained in this Agreement or any policy or guideline referenced herein at any time and in its sole discretion.</li>
   <li>OvalFleet reserves the right to change any and all content contained on the Sites at any time without notice. Reference to any products, services, processes, or other information, by trade name, trademark, manufacturer, supplier, or otherwise does not constitute or imply endorsement, sponsorship or recommendation thereof by OvalFleet.</li>
   <li>YOUR RESPONSIBILITY AND RISK. It is solely your responsibility to evaluate the accuracy, completeness, and usefulness of all opinions, advice, services, merchandise, and other information provided on or through the Sites or on the Internet generally. The Internet contains unedited materials. You access such materials at your risk. OvalFleet has no control over and accepts no responsibility whatsoever for such materials.</li>
   <li>This electronic document and any other electronic documents, policies, and guidelines incorporated herein will be: (a) deemed for all purposes to be a "writing" or "in writing," and to comply with all statutory, contractual, and other legal requirements for a writing; (b) legally enforceable as a signed writing as against the parties subject to the electronic documents; and (c) deemed an "original" when printed from electronic records established and maintained in the ordinary course of business. Electronic documents introduced as evidence in any judicial, arbitration, mediation, or administrative proceeding will, if established and maintained in the ordinary course of business, be admissible to the same extent as business records in written form that are similarly established and maintained.</li>
   <li>OvalFleet failure to insist upon or enforce strict performance of any provision of this Agreement shall not be construed as a waiver of any provision or right. Neither the course of conduct between the parties nor trade practice shall act to modify any provision of this Agreement. OvalFleet may assign its rights and duties under this Agreement to any party at any time without notice to you.</li>
   <li>Customer Responsibilities: (A) Customer shall, at its sole cost, be responsible: (1.) for providing all equipment (PC, Laptops, Mobile Devices, and Similar Equipment), operating software, IT security, peripheral equipment, facilities and IP connectivity (including connectivity to Subscribers) necessary for the OvalFleet Application and the Customer network to operate OvalFleet Solutions; (B.) to obtain and provide OvalFleet, prior to connectivity of the particular OvalFleet Service a valid email address.</li>
   <li>How do we safeguard your data: In order to ensure the confidentiality and integrity of sensitive information, data encryption is a key element employed with OvalFleet Services. New and evolving data security policies make data encryption necessary to safeguard our customers sensitive information against unauthorized disclosure, inspection, and modification. We employ active governance to help ensure that we keep customer data and the confidentiality of information secure.</li>
   <li>Personal Information: We collect and use personal information about you in order to establish and manage our business relationship with you. We share such information about you with our Authorized Service Teams in order to provide service. You give us your consent to disclose information about you for the following purposes:<br>
    i. Billing and/or supplying services to you under the Agreement;<br>
    ii. Law enforcement;<br>
    iii. Complying with a legal requirement; and<br>
    iv. Processing of past due accounts of yours which have been passed to a debt collection agency.<br>
    v. In order to maintain privacy of account and other proprietary customer information, we may request you provide us with certain information to verify your identity. You and any authorized representative you may designate on the account will be required to provide such verification information before we will release any information related to your account or make any changes to the account. Unless you tell us otherwise, you also give us your consent to use and disclose your personal information to make you aware of our other products and services that may be of interest to you.
  </li>
   <li>Warranties: OvalFleet makes no express warranties except those stated in this section and in OvalFleet applicable limited warranty statement in effect on the date of the invoice, packing slip or the documentation provided with the product(s). OvalFleet disclaims all other warranties, express or implied, including without limitation implied warranties of non-infringement, merchantability and fitness for a particular purpose. There are no warranties by OvalFleet for non-OvalFleet branded products, service or software products. All such products are provided by OvalFleet "as is". No revision in limited warranties will affect products already ordered by you.</li>
   <li>Products: OvalFleet policy is one of on-going Product update and revision. OvalFleet may revise and discontinue Products at any time without notice to you. OvalFleet will ship Products that have the functionality and performance of the Products ordered, but changes between what is shipped and what is described in a specification sheet or catalog are possible. The parts and assemblies used in building Products and spare parts are selected from new, equivalent-to-new or reconditioned parts and assemblies.</li>
   <li>Service and Support: Service offerings may vary from product to product. If you purchase optional services and support, OvalFleet or a third party service provider will provide the optional service and support to you or your customer in the United States in accordance with the terms and conditions in effect at the time of your purchase. OvalFleet may, at its discretion, revise its general and optional service and support programs and the terms and conditions that govern them without prior notice to you or your customer. OvalFleet has no obligation to provide warranty or support services to you or your customers until OvalFleet has received full payment for the product that you purchase.</li>
   <li>Fraud: OvalFleet shall have the right to refuse or discontinue service or service arrangements without advance notice, if the acts of the Customer or the conditions upon their premises are such as to indicate an intent to defraud OvalFleet or to use the service to defraud a third party, including but not limited to, providing false credit information, significantly misstating expected service volumes, using the service for unlawful purposes, using the services in a manner that violates the law, or using services without intent to pay. Customer is responsible for all charges attributable to customer, even if incurred because of fraudulent or unauthorized use of the service by third parties. OvalFleet may, but is not obligated to, detect or report unauthorized or fraudulent use of service.</li>
   <li>For purposes of this agreement, “Confidential information” includes, but is not limited to, any and all information furnished or disclosed, in whatever form or medium, concerning a transmitting party, including without limitation, the following forms of information and other information or any nature (whether or not reduced to writing):<br>
    i. Rights to copyrights, trademarks, trade names<br>
    ii. Discoveries or processes<br>
    iii. Ideas or concepts<br>
    iv. Computer software, including object codes, source codes, flow charts, diagrams and documentation<br>
    v. Pricing methods, financial data, customer or supplier lists, statistics, databases<br>
    vi. Marketing and development concepts and plans<br>
    vii. Techniques and procedures, processes, systems, or configurations<br>
    viii. Operating policies and procedures.
  </li>
   <li>Obligation not to use information to compete: The parties and their representatives shall not use any confidential information or any information derived therefrom for the purposes of competing with the other party or enabling others to compete with the other party.</li>
   <li>YOUR INDEMNITY TO OVALFLEET. To the fullest extent permitted by law, you will indemnify, defend and hold OvalFleet, including OvalFleet partners, officers, directors, agents, employees, subsidiaries, affiliates, parents, successors and assigns, harmless from any claim, demand, cause of action, debt or liability (including reasonable attorney’s fees, expenses and court costs) arising from: (a) your modification(s) of and/or addition(s) to Product(s); (b) your breach of this Agreement, (c) your omissions, misrepresentations, or negligence, and (d) the Products sold by you damage a third party to the extent such claim is based on (i) your modification of and/or addition to the Products, misuse or abuse of the Products, negligence or breach of any provision in this Agreement; (ii) your failure to abide by all applicable laws, rules, regulations and orders that affect the Products; (iii) your omission, misrepresentation, or negligence, or (iv) you or your end-users cause intentional harm to any person or property. Indemnified claims, debts and liabilities include the amount of any discount in price or concession that is made available by OvalFleet to you.</li>
   <li>Payment Terms; Orders; Quotes; Interest: Terms of payment are within OvalFleet sole discretion, and unless otherwise agreed to by OvalFleet, payment must be received by OvalFleet prior to OvalFleet acceptance of an order. Payment for the products will be made by credit card, wire transfer, or some other prearranged payment method. Invoices are due and payable within the period noted in the invoice, measured from the date of the invoice. OvalFleet may invoice parts of an order separately. Your order is subject to cancellation by OvalFleet, at OvalFleet sole discretion. Unless you and OvalFleet have agreed to a different discount, OvalFleet standard pricing policy for OvalFleet systems, which include both hardware and services in one discounted price, allocates the discount off list price applicable to the service portion of the system to be equal to the overall calculated percentage discount off list price on the entire system. OvalFleet is not responsible for pricing, typographical, or other errors, in any offer by OvalFleet, and reserves the right to cancel any orders resulting from such errors.</li>
   <li>Limitation of Liability. OvalFleet does not accept liability beyond the remedies set forth herein, including but not limited to any liability for product not being available for use, lost profits, loss of business or for lost or corrupted data or software, or the provision of services and support. Except as expressly provided herein, OvalFleet will not be liable for any consequential, special, indirect, or punitive damages, even if advised of the possibility of such damages, or for any claim by any third party. You agree that for any liability related to the purchase of product, OvalFleet is not liable or responsible for any amount of damages above the amount invoiced for the applicable product. Notwithstanding anything in this agreement to the contrary, the remedies set forth in this agreement shall apply even if such remedies fail their essential purpose.</li>
   <li>Additional Remedies & Responsibilities. OvalFleet reserves the right to discontinue or otherwise void any warranty, service or technical support it offers in whole or in part if you breach any of your obligations under this agreement or if you fail to pay amounts due for products you purchase from OvalFleet. You shall be solely responsible for all representations or omissions you make to your customers including but not limited to any representation or omission you make about product warranties, features, performance, support and service. You will inform your customers of OvalFleet rights and your obligations under this agreement.</li>
   <li>Governing Law: This Agreement will be governed by, and be construed and interpreted in accordance with the laws of the State of Texas, United States of America. The Denton and/or Dallas County Court of Texas, United States of America shall be the agreed forums for resolution of all disputes with respect to the rights and obligations of the signatories to this Agreement. The Laws of Texas govern this Agreement, excluding its conflicts of laws rules and excluding the United National Convention on the international Sale of Goods. Further, your use of our service and/or products shall comply with all applicable domestic and international laws, statutes, ordinances and regulations.</li>
   <li>General: The software and documentation accompanying OvalFleet solutions whether on disk, in read only memory, on any other media or in any other form (collectively the OvalFleet Software") are licensed, not sold, to you by OvalFleet("OvalFleet, LLC") for use only under the terms of this agreement, and OvalFleet reserves all rights not expressly granted to you. The rights granted herein are limited to OvalFleet and its licensors' intellectual property rights in the OvalFleet Software and do not include any other patents or intellectual property rights. You own the media on which the OvalFleet Software is recorded but OvalFleet and/or OvalFleet licensor(s) retain ownership of the OvalFleet Software itself. The rights granted under the terms of this License include any software upgrades that replace and/or supplement the original OvalFleet Software product, unless such upgrade contains a separate license.</li>
   <li>Miscellaneous: You may not publicly release any information relating to this agreement, including the existence of this Agreement, without first receiving the prior express written approval of OvalFleet. OvalFleet grants no licenses or other rights, title or interest under this Agreement. To give notice under this Agreement, the notice must be in writing and will be effective when received by the other party. For notices to OvalFleet notice will be sent to OvalFleet, Attn: CTC Connections, 1009 Jupiter Road, Plano, TX 75074-3734. If any provision of this Agreement is void or unenforceable, the reminder of this agreement will remain in full force and will not be terminated. Neither party will be liable for any delays resulting from circumstances nor causes beyond the party’s reasonable control. Your obligations related to confidentiality, payment, purchase codes, security interest, indemnification, general regulatory compliance and miscellaneous provisions in this section as well as provisions related to warranties and limitation of liability will survive any termination or expiration of this Agreement. Except in the case of OvalFleet or its subsidiaries and Parent Corporation, neither party may assign this Agreement. No provision of this Agreement will or shall be deemed to create a partnership, joint venture or other combination between you and OvalFleet. You and OvalFleet are independent contractors. Neither party will make any warranties or representations or assume any obligations on the other party’s behalf. Neither party is nor will claim to be a legal representative, partner, franchisee, agent, or employee of the other party. Each party is responsible for the amounts it incurs arising from this Agreement and for the direction and compensation, and is liable for the actions of, its employees, and subcontractors. This Agreement is the entire agreement between OvalFleet and you with respect to its subject matter and supersedes all prior verbal and written understandings, communications or agreements between you and OvalFleet. No amendment to or modification of this Agreement, in whole or part, will be valid or binding unless it is in writing and executed by authorized representatives of both parties.</li>
   <li>Any errors in this agreement do not void the contents in part or in whole.</li>
   <li>Any action we take or fail to take does not mean that we give up any of our rights under this Agreement.</li>
   <li>All services and products are subject to the OvalFleet Service Agreement (Service Terms) found on this page.</li>
   <li>We will make commercially reasonable efforts to fulfill our obligations under this Agreement. Certain causes and events that are out of our reasonable control (“Force Majeure Event(s)”) may result in our inability to perform under this Agreement. If we are unable to perform our obligations, in whole or in part, due to a Force Majeure Event, then our obligations shall be suspended to the extent made necessary by such Force Majeure Event, and in no event shall we be liable to you for damages caused by any Force Majeure Event. Force Majeure Events include, but are not limited to, acts of God, fire, war, flood, earthquake, acts of terrorism, acts of any governmental authority, accidents, strikes, labor troubles, shortages in supply, changes in laws, rules, or regulations of any governmental authority, or any other cause beyond our reasonable control.</li>
   <li>This agreement is effective upon acceptance and/or first use of our services and/or products signifies acceptance and agreement to OvalFleet Service Agreement (Service Terms).</li>
 </ul>